### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by haf** [maxmantz/redux-oidc-example#4]
```
$ npm install && npm start
$ open https://localhost:8080/
...
Uncaught Error: Cannot find module "immutable"
    at webpackMissingModule (https://127.0.0.1:8080/app.js:31276:131)
    at t.(anonymous function).exports (https://127.0.0.1:8080/app.js:31276:217)
    at Object.<anonymous> (https://127.0.0.1:8080/app.js:31276:541)
    at __webpack_require__ (https://127.0.0.1:8080/app.js:20:30)
    at Object.<anonymous> (https://127.0.0.1:8080/app.js:29489:19)
    at __webpack_require__ (https://127.0.0.1:8080/app.js:20:30)
    at Object.<anonymous> (https://127.0.0.1:8080/app.js:8701:13)
    at __webpack_require__ (https://127.0.0.1:8080/app.js:20:30)
    at Object.<anonymous> (https://127.0.0.1:8080/app.js:72:19)
    at __webpack_require__ (https://127.0.0.1:8080/app.js:20:30)
webpackMissingModule @ redux-oidc.js:1
t.(anonymous function).exports @ redux-oidc.js:1
(anonymous) @ redux-oidc.js:1
__webpack_require__ @ bootstrap 9b09fd9…:19
(anonymous) @ app.js:3
__webpack_require__ @ bootstrap 9b09fd9…:19
(anonymous) @ index.js:3
__webpack_require__ @ bootstrap 9b09fd9…:19
(anonymous) @ bootstrap 9b09fd9…:39
__webpack_require__ @ bootstrap 9b09fd9…:19
(anonymous) @ bootstrap 9b09fd9…:39
(anonymous) @ bootstrap 9b09fd9…:39
```

**Comment by maxmantz** [comment]
Somehow immutable was missing in `package.json`. I've fixed this. Just pull my latest changes and try building again.

**Comment by haf** [comment]
Super!
